- src/xgboost_lib.jl
It would be useful to allow xgboost() to be fully silent. This pull request is an idea about how to do that...by leaving the default behavior unchanged, but going fully silent when silent=1.
> Allow xgboost() to be fully silent

- src/xgboost_lib.jl
There was no way to specify this parameter before, and _set_info was also broken for setting group information
> Support "group" parameter for xgboost

- deps/build.jl
The API for XGBoost master changed last week. So this locks new installs to the last v0.4 release and also ensures submodules are correctly checked out.
> Now locked to xgboost version 0.47 to fix builds.

- src/xgboost_lib.jl
Fix in line with Python wrapper. 
See https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/sklearn.py#L87
and https://github.com/dmlc/xgboost/pull/788 for reference
> Fix missing to be NaN in line with latest Python bindings

- demo/cross_validation.jl
Trivial comment before parameter definition.
As this is a walk-through, would it be better to specify/explain the general, boost and task parameters separately with comments?
> Added comment before parameter assignment

- src/xgboost_lib.jl
Since the `transposed` argument is shared between dense and sparse constructors but the `missing` argument is not, I moved `missing` to the end of the argument list to allow `DMatrix(data,
true)` (which treats the data as transposed) to dispatch correctly for both sparse and dense arguments.
This is a breaking change. But the `missing` argument seems little used, and type-checks will flag an issue for anyone dependent on that argument.
> Make sparse and dense constructors consistent

- .travis.yml
This package currently support `osx` while it didn't open tests on `osx` in .travis.yml.
The result is shown at [my own travis-ci](https://travis-ci.org/zhmz90/XGBoost.jl).
> add osx support on travis

- REQUIRE
There were too many issues with adding v0.3 support, so I think it is best to just stick with v0.4 for Julia. Since the current tagged release does not compile for either v0.4 or v0.3, for now tagging a 0.4 only release will only improve things.
> Require Julia v0.4

- .travis.yml
- README.md
- REQUIRE
- demo/README.md
- demo/basic_walkthrough.jl
- demo/cross_validation.jl
- demo/custom_objective.jl
- demo/predict_first_ntree.jl
- deps/build.jl
- src/XGBoost.jl
- src/xgboost_lib.jl
- src/xgboost_wrapper_h.jl
- test/example.jl
- test/runtests.jl
- test/utils.jl
This PR is a general update of the XGBoost.jl package, providing support for the latest stable and master versions of XGBoost and ensuring portability of the package code.
Most notably, the PR defaults to building the latest stable version (0.60) of the XGBoost library, but adds the option to build the latest master version. To support this, the Julia wrapper now uses Julia's system independent c types and automatically switches the appropriate type definitions based on the library version (stable or master). This also fixes https://github.com/dmlc/XGBoost.jl/issues/24.
In addition, the PR includes several minor improvements, namely:
- The package will now use precompilation.
- Fixed several spelling errors.
- No longer needs `eval()` in the wrapper macro.
- Improved formatting …
> Support building latest stable and master XGBoost + Julia code update

- deps/build.jl
because 0.80 fails to compile, at least on Linux with the following error:
```
│ g++ -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -fPIC -DDISABLE_OPENMP src/data/data.cc -o build/data/data.o
│ In file included from src/data/data.cc:10:0:
│ src/data/./simple_dmatrix.h:19:7: error: looser throw specifier for 'virtual xgboost::data::SimpleDMatrix::~SimpleDMatrix() noexcept (false)'
│  class SimpleDMatrix : public DMatrix {
│        ^
│ In file included from src/data/data.cc:5:0:
│ include/xgboost/data.h:347:11: error:   overriding 'virtual xgboost::DMatrix::~DMatrix() noexcept'
│    virtual ~DMatrix() = default;
│            ^
│ Makefile:141: recipe for target 'build/data/data.o' failed
│ make: …
```
> bump xgboost version to 0.82

- src/XGBoost.jl
- src/rabit_wrapper.jl
- src/xgboost_lib.jl
- src/xgboost_wrapper_h.jl
- test/rabit.jl
- test/runtests.jl
Expose the following Rabit APIs to help with multi-machine parallelization:
- `rabit_init`
- `rabit_finalize`
- `rabit_is_distributed`
- `rabit_get_rank`
- `rabit_get_world_size`
- `rabit_get_version_number`
> expose few Rabit APIs to help in parallelization

- test/example.jl
Explicitly calls XGBoost.save method, without which it throws error
> fixes xgboost test on windows

- .travis.yml
also makes sure CI runs on latest bug fix version of 1.0 and 1.2
> Enabling CI for windows

- Project.toml
- src/xgboost_lib.jl
- src/xgboost_wrapper_h.jl
- test/dump.nice.json
- test/dump.raw.json
- test/example.jl
Provide the option of dump_model in JSON format. JSON format provides easier access to the tree structure (does not require parsing the dump file).
XGBoost allows providing file format options for the model_dump such as JSON format (see [here](https://github.com/dmlc/xgboost/pull/1726)). This pull request adds the capability to the Julia Wrapper.
> add dump_model file format option

- src/XGBoost.jl
- src/xgboost_lib.jl
Hello
Recantly I get puzzled on getting same random numbers when I was using `nfold_cv` to testify parameters. After reading the source code of that function, I don't think it's proper to change the global random seed.
So I have done some changes on the source code to fix that problem.
1. remove the importing of `Random:seed!`
2. import `Random:MersenneTwister` as seed generator
3. generate `randidx` using local seed without changing global seed
> Generate random indics using local seed rather global seed in cv

- .github/workflows/ci.yml
My bad. I missed this when reviewing https://github.com/dmlc/XGBoost.jl/pull/111.
> Run CI on `master` too

- .gitignore
- Project.toml
- src/booster.jl
- test/runtests.jl
Added some testing to verify that the save/load/serialize functionality is working as expected. I am not sure the best way to compare if loading in a booster worked correctly other than comparing predictions.
This PR includes changes from https://github.com/dmlc/XGBoost.jl/pull/125, and the typo mentioned here https://github.com/dmlc/XGBoost.jl/issues/126
> Add tests for saving/loading/serializing boosters

- Project.toml
- docs/src/api.md
- src/XGBoost.jl
- src/dmatrix.jl
- test/runtests.jl
This is a more aggressive version of #129.
I got rid of the `DataTuple` alias altogether as it was not doing anything at this point.  It was probably left over from an earlier draft of my big PR.  Users are now responsible for making sure tuple types are correct.  Also added a test case for an example like the one in the docs.
> make DMatrix constructors more permissive to accommodate table arguments

- src/introspection.jl
In updating some code to v2, I ran into cases where a booster ended up as a null model and then `importance` would fail because `fns` here was empty.
> Fix `importance` when no features are used

- Project.toml
- docs/src/index.md
- src/Lib.jl
- src/XGBoost.jl
- src/dmatrix.jl
- src/show.jl
- test/runtests.jl
This is added by virtue of the new `XGDMatrixGetDataCSR` method in libxgboost 1.7 which is now required.  Unit tests for `DMatrix` constructors have been vastly improved as they now check that the matrices were actually constructed correctly rather than merely having the same shape.
The behavior I'm seeing in the presence of null values doesn't make sense to me, so [this issue](https://github.com/dmlc/xgboost/issues/8459) is going to have to be resolved before this gets merged.
> DMatrix is now an AbstractMatrix

- Project.toml
- src/XGBoost.jl
- src/booster.jl
I don't really like changing the default parameters will-he nill-he but multiple of us have gotten pretty annoyed by this so this PR turns on warnings for invalid parameter names by default.
It suffers from the usual issue of having its own stderr output so we can't run it through the Julia logger.
> validate parameter names by default

- .github/workflows/ci.yml
- Project.toml
- docs/src/features.md
- docs/src/index.md
- src/show.jl
I modified the PR [here](https://github.com/dmlc/XGBoost.jl/pull/141) using @ExpandingMan's suggested method for proper type inference. I am interested in having this feature, so I went ahead and created a PR with all the changes because the other one hasn't had activity recently. 
Here is a MWE to replicate the results:
```julia
julia> using DataFrames
julia> using Random; Random.seed!(3);
julia> using XGBoost
julia> df = DataFrame(randn(10,3), ["kirk", "spock", "bones"])
10×3 DataFrame
Row │ kirk       spock       bones      
│ Float64    Float64     Float64    
─────┼───────────────────────────────────
1 │  0.663934  -0.419345   -0.489801
2 │  1.19064    0.420935   -0.321852
3 │  0.713867   0.293724    0.0450463
4 │ -1.3474    -0.402996    1.50831
5 │ -0.458164   0.0399281  -0.83443
6 …
```
> Display Split conditions

- Project.toml
- src/booster.jl
- test/runtests.jl
Prompted by #163 I discovered that the C API expects certain parameters to be set via multiple separate calls.  Currently the only way to do this is via multiple calls to `setparam!`.  This PR adds that ability to reproduce the same behavior with an `AbstractVector` or `Tuple`.
> add ability to set multi-valued booster params

- Project.toml
At least in some cases tree display looks wonky with 2.0 but this may not be a new issue and I would not consider that "breaking".
> expand compat bounds for Term.jl

- Project.toml
- ext/XGBoostTermExt.jl
- src/dmatrix.jl
- test/runtests.jl
Somehow I had previously missed the fact that the Term extension was no longer even creating `show` methods.  With this fix, Term panels will show for the `"text/plain"` mime type when Term is loaded.
Additionally, there is a small fix for CUDA-backed tables in an issue that's caught in a test but not in CI/CD because of lack of CUDA.
> fixes for Term extension

- Project.toml
- docs/src/api.md
- src/booster.jl
- test/runtests.jl
> copy predicted array so we dont overwrite used memory location

- Project.toml
- src/Lib.jl
- src/booster.jl
- src/dmatrix.jl
- test/runtests.jl
This updates to `libxgboost` version 2.0 thanks to @tylerjthomas9 update of the JLL.
Surprisingly little seems to have changed (at least as far as breaking changes in the interface are concerned).  The only real difference seems to be in model and `DMatrix` inputs and outputs, which appear to have been sanitized somewhat.  `libxgboost` now requires the format of a file from which a `dmatrix` is loaded to be explicitly specified.  Unfortunately, in order for this not to cause a breaking change, we have to default this format to `libsvm`.  This is undesirable because `save` exports a different file format, which `libxgboost` does not name which I am calling `:binary`.  I badly wanted to change this, but I can't justify breaking it.  Furthermore, saving boosters in a binary format using …
> update to libxgboost 2.0

- Project.toml
Didn't even fully test this locally since I can't get `CEnum` `0.5` to install on my env and it's the weekend and I'm being lazy, but let's see how tests do.
> bump CEnum

- docs/src/index.md
- src/booster.jl
- test/runtests.jl
Had a need for early stopping rounds and followed the discussion found here https://github.com/dmlc/XGBoost.jl/issues/158 to implement this version of it.
> Add functionality for early stopping rounds.

- Project.toml
- src/XGBoost.jl
- src/booster.jl
- test/runtests.jl
The recent addition of early stopping rounds broke the ability to pass `watchlist` as `NamedTuple`.  Probably not narrowing the type in the first place was a mistake, and we should have picked one, but in the meantime it would be breaking to remove either.  This PR restores the ability to pass `watchlist` as any iterable of pairs of which the keys can be converted to strings.
See https://github.com/JuliaAI/MLJXGBoostInterface.jl/issues/46#issuecomment-1821235496
> allow watchlist to be NamedTuple

- .github/workflows/IntegrationTest.yml
Based on https://github.com/TuringLang/Libtask.jl/blob/master/.github/workflows/IntegrationTest.yml.
> Add integration test

- Project.toml
- src/Lib.jl
- test/runtests.jl
This is to fix the issue mentioned [here](https://github.com/JuliaPackaging/Yggdrasil/issues/11918) where XGBoost wasn't working when users had CUDA v13 present. Now the behaviour of the package is to attempt to load GPU-compatible artifacts for XGBoost via XGBoost_GPU_jll, but if it can't find a compatible artifact it falls back to the standard CPU build in XGBoost_jll
> Separate XGBoost JLL package into CPU and GPU versions
